### ISSUE TITLE
Deploy to gh-pages?

### ISSUE THREAD

**Issue by YoRHa-A5** [nano-react-app/nano-react-app#14]
Hi,

There are a lot of tutorials for deploying projects to github pages using [gh-pages](https://github.com/tschaub/gh-pages).
I tried deploying one made with nano-react-app (with `"deploy": "gh-pages -d dist"`) but when trying to access the page, the GET for the src.xyz.js throws a `net::ERR_ABORTED 404` error.
Manual access to the .js file using the browser address bar works, though.

What am I missing?
Thanks in advance.

**Comment by adrianmcli** [comment]
Can you post a reproduction repo?

**Comment by YoRHa-A5** [comment]
> Can you post a reproduction repo?

Sure, take a look at my [ToDo List](https://github.com/BunnyTheLifeguard/todo-list-react)

**Comment by adrianmcli** [comment]
I found the problem, we need a `<!DOCTYPE html>` at the top of the HTML file. I'll add it in, thanks.

**Comment by adrianmcli** [comment]
Should be working now.

**Comment by adrianmcli** [comment]
Hmm, seems like there's still a problem. Parcel replaces this relative path:

```html
<script src="./src/index.js"></script>
```

with this absolute path after compilation:

```html
<script src="/src.3f7186c9.js"></script>
```

Unfortunately, if your app is not deployed at the top-level domain, it will try to look for the JS file in the wrong place.

For example, if your deployed your `todo-list-react` in `http://<username>.github.io/todo-list-react`, then it will look for the JS file at `http://<username>.github.io/src.3f7186c9.js` instead of `http://<username>.github.io/todo-list-react/src.3f7186c9.js`

I'm not sure how to fix this, this is a [Parcel](https://github.com/parcel-bundler/parcel) problem after all. Perhaps you can post on their issue tracker? I can keep this open for now.

**Comment by YoRHa-A5** [comment]
Got it to work using [this](https://github.com/parcel-bundler/parcel/issues/236#issuecomment-351132623) @adrianmcli 

Maybe worth including
```
"build": "parcel build index.html --public-url '.'", 
"predeploy": "rm -rf dist && parcel build index.html --public-url '.'",
```
in an update?
