### ISSUE TITLE
Much better tooling out there now guys!

### ISSUE THREAD

**Issue by algoflows** [nano-react-app/nano-react-app#29]
Have you thought to upgrade to either snowpack or vite based on esbuild?!

**Comment by adrianmcli** [comment]
Yea I'm open to it. Any thoughts?

**Comment by mgreasly** [comment]
I was interested in the mentioned tooling, I created a template that uses snowpack instead of Parcel if you want to integrate from https://github.com/mgreasly/template-jsx.

I didn't include references to static files/'public' folder etc and kept the template to the same minimal functionality as the original (because that's the desired effect). You could have a more fully featured template but then, hey, you're getting back towards create-react-app again.

**Comment by adrianmcli** [comment]
@mgreasly nice job. I'm all for migrating nano-react-app to Snowpack. In fact, if you'd like to take over this project as maintainer, I'm happy to support you and make you a member of the org. Might be a good idea since this project has 562 github stars already and I don't have a lot of bandwidth these days. perfectly fine if u don't want to join as well, just thought I'd offer.

**Comment by mgreasly** [comment]
Yes, I'd love to get involved.  I'm a big fan of the project and keen to make sure it stays up to date. 
I'm not promising a super amount of bandwidth or updates - I'm happy with keeping things up to date and simple to use. I mainly fiddle with example code these days, I'm happy with a minimal react project without bells and whistles.

**Comment by adrianmcli** [comment]
@mgreasly that sounds great. I've added you as a collaborator to the org and all the repos. I don't expect there to be much bandwidth requirement and I'll still be around.

**Comment by mgreasly** [comment]
Thanks @adrianmcli . I created a new template using both of the suggestions (snowpack/vite) to see if there's any real difference. I would lean slightly towards Vite as it has OOTB typescript support, you need an additional add-on for snowpack. Other than that, they are both nice and quick with no config. Any thoughts/prefs on which to use?

**Comment by kotx** [comment]
It seems snowpack does support TypeScript OOTB. https://www.snowpack.dev/reference/supported-files#typescript
> Snowpack includes built-in support to build JSX files (*.jsx & *.tsx) to JavaScript.

I might be misunderstanding though.

Also, it seems the authors of SvelteKit decided to use [Vite instead of Snowpack](https://svelte.dev/blog/sveltekit-beta#From_Snowpack_to_Vite), due to features like CSS code-splitting and rollup backwards-compatibility that might be desirable for users of this template.

**Comment by mgreasly** [comment]
thanks I'll give it a quick try - I'd added the plugin, but if it's not needed then it's much of a muchness between them (at least in terms of initial config/support for the template). Speed performance seemed the same between them but the template is only 2 files so no idea how they scale.

**Comment by mgreasly** [comment]
Yeah, so you're 100% right - snowpack is fine with defaults/no config for typescript. Happy with either myself - I've got either version here - @adrianmcli , do you have any preference for snowpack or vite?

**Comment by adrianmcli** [comment]
Good question, I actually began with a preference for Snowpack. But after looking into Vite a bit more, I think I'm leaning more towards Vite. Because it requires fewer packages (i.e. cleaner `package.json`) and it was actually inspired by Snowpack so we can assume that it is looking to improve upon Snowpack. They're both very minimal bundlers, so there's no wrong answer but if I had to choose, I'd say Vite.

It's also got a bigger community (32.7k stars vs 19.4k stars) and growing usage on NPM:

![snowpack,vite](https://user-images.githubusercontent.com/943555/137678227-fb1f4359-7542-4ab6-b0b3-b1033d1bd980.png)

Source: https://npmcharts.com/compare/snowpack,vite

**Comment by mgreasly** [comment]
@adrianmcli , I've raised a PR against template-js to use Vite instead of Parcel - https://github.com/nano-react-app/template-js/pull/18.
Give it a test & make sure it builds etc. I'll create a PR in the typescript template as well once this is done.

We'll need to update the readme in nano-react-app just to say Vite not Parcel, can do that once we're good here.

**Comment by adrianmcli** [comment]
I ran it and it works fine, thanks @mgreasly! Feel free to merge.

**Comment by mgreasly** [comment]
Merged for the js template, I'll raise a PR for the update to the ts template as well.

**Comment by mgreasly** [comment]
@adrianmcli I've updated template-ts and raised a PR to it. Want to pull it and build to check it's good and we can merge?

**Comment by adrianmcli** [comment]
Approved.

**Comment by mgreasly** [comment]
Ok, ts template merged as well. We're now using Vite! I'll close this issue now
